module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  comment: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  inline_form_errors: 0
  jsonapi: 0
  jsonapi_extras: 0
  link: 0
  media: 0
  media_library: 0
  menu_ui: 0
  mutual8_core: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  rules: 0
  serialization: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  typed_data: 0
  user: 0
  views_ui: 0
  webhooks: 0
  menu_link_content: 1
  views: 10
  mutual8: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
profile: mutual8
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
